import { useState } from 'react'
import { ClipboardCheck, FileSearch, History, ShieldCheck, UserCheck } from 'lucide-react'
import { PageHeader } from '@/components/layout/PageHeader'
import { DataTable, type Column } from '@/components/ui/DataTable'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { incidents } from '@/data/incidents'
import { verificationQueue } from '@/data/intelligence'
import type { AdminUser } from '@/types/system'
const USERS:AdminUser[]=[{id:'u1',name:'A. Sharma',role:'IMD Official',region:'National',status:'active'},{id:'u2',name:'R. Iyer',role:'State Official',region:'Tamil Nadu',status:'active'},{id:'u3',name:'P. Das',role:'Analyst',region:'West Bengal',status:'active'},{id:'u4',name:'K. Verma',role:'Reviewer',region:'National',status:'active'},{id:'u5',name:'S. Nair',role:'District Official',region:'Kerala',status:'idle'}]
const cols:Column<AdminUser>[]=[{header:'User',cell:u=>u.name},{header:'Role',cell:u=>u.role},{header:'Region',cell:u=>u.region},{header:'Status',cell:u=><span className={u.status==='active'?'text-success':'text-ink-faint'}>{u.status}</span>}]
export default function AdminPanel(){const[queue,setQueue]=useState(verificationQueue.map(q=>({...q,cleared:false})));return <div className="space-y-6 p-6"><PageHeader title="Admin Panel" description="Human review, provenance, roles and audit decisions — the final control layer for VARSHAA."/><div className="grid gap-3 sm:grid-cols-3"><Kpi icon={FileSearch} label="Pending review" value={queue.filter(q=>!q.cleared).length.toString()}/><Kpi icon={ShieldCheck} label="AI screened" value="91%"/><Kpi icon={History} label="Audit events" value="1,842"/></div><div><h3 className="mb-2 text-sm font-semibold text-ink">Users & Roles</h3><DataTable columns={cols} rows={USERS} rowKey={u=>u.id}/></div><div><h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-ink"><ClipboardCheck className="h-4 w-4 text-primary"/> Verification queue</h3><div className="space-y-2">{queue.map(q=><div key={q.id} className={`rounded-xl2 border border-border bg-surface p-4 ${q.cleared?'opacity-40':''}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[13px] font-semibold text-ink">{q.id} · {q.location}</div><div className="mt-1 text-[11px] text-ink-muted">{q.event} · {q.language} · Evidence {q.score}/100</div><div className="mt-1 text-[11px] text-ink-faint">{q.reason}</div></div><div className="flex gap-2"><Button size="sm" disabled={q.cleared} onClick={()=>setQueue(v=>v.map(x=>x.id===q.id?{...x,cleared:true}:x))}><UserCheck className="h-3.5 w-3.5"/> Verify</Button><Button size="sm" variant="outline" disabled={q.cleared} onClick={()=>setQueue(v=>v.map(x=>x.id===q.id?{...x,cleared:true}:x))}>Needs evidence</Button></div></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Audit label="Source" value="Citizen + weather"/><Audit label="Location" value="Cluster match"/><Audit label="Decision" value={q.cleared?'Recorded':'Pending reviewer'}/></div></div>)}</div></div><Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><History className="h-4 w-4 text-primary"/> Audit trail preview</div><div className="mt-3 space-y-2 text-[11.5px]">{incidents.slice(0,4).map((i,n)=><div key={i.id} className="flex gap-3 border-b border-border pb-2"><span className="text-ink-faint">14:{31-n*3}</span><span className="text-ink"><b>{i.id}</b> · {n===0?'risk escalated':n===1?'human verification recorded':n===2?'duplicate cluster merged':'evidence score updated'}</span></div>)}</div></Card></div>}
function Kpi({icon:Icon,label,value}:{icon:typeof FileSearch;label:string;value:string}){return <Card className="p-4"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase text-ink-muted"><Icon className="h-3.5 w-3.5 text-primary"/>{label}</div><div className="mt-1 text-2xl font-bold text-ink">{value}</div></Card>}
function Audit({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-canvas p-2"><div className="text-[9px] uppercase text-ink-faint">{label}</div><div className="mt-0.5 text-[11px] font-medium text-ink">{value}</div></div>}
