import { useEffect, useState } from 'react'
import { ArrowUpRight, BellRing, CheckCircle2, Clock3, Languages, ShieldAlert } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { PageHeader } from '@/components/layout/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { alertService } from '@/services/alertService'
import type { AlertDraft } from '@/types/alert'

interface FormValues { title:string; event:string; region:string; severity:AlertDraft['severity']; description:string; recommendedActions:string }
const ESCALATION=[{time:'14:08',level:'Moderate',reason:'Initial citizen reports'},{time:'14:24',level:'High',reason:'Ground-truth gap detected'},{time:'14:31',level:'Critical',reason:'Rainfall + cluster growth + impact increase'}]
export default function Alerts(){const[alerts,setAlerts]=useState<AlertDraft[]>([]);const[preview,setPreview]=useState<AlertDraft|null>(null);const{register,handleSubmit,reset}=useForm<FormValues>({defaultValues:{title:'',event:'Flood',region:'',severity:'High',description:'',recommendedActions:''}});useEffect(()=>{alertService.getAlerts().then(setAlerts)},[]);const onSubmit=async(v:FormValues)=>{const d=await alertService.generateAlert({...v,languages:['English','Hindi','Marathi']});setAlerts(a=>[d,...a]);setPreview(d);reset()};return <div className="space-y-5 p-6"><PageHeader title="Alert Command" description="Turn verified incidents into explainable, multilingual, impact-based alerts."/><div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
<Card><div className="flex items-center gap-2 font-semibold text-ink"><BellRing className="h-4 w-4 text-primary"/> Active alert drafts</div><div className="mt-3 space-y-2.5">{alerts.map(a=><button key={a.id} onClick={()=>setPreview(a)} className="block w-full rounded-lg border border-border p-3 text-left hover:bg-canvas"><div className="flex justify-between text-[13px] font-semibold text-ink"><span>{a.title}</span><span className={a.severity==='Critical'?'text-danger':a.severity==='High'?'text-warning':'text-primary'}>{a.severity}</span></div><div className="mt-1 text-[12px] text-ink-muted">{a.region} · {a.createdAt}</div><div className="mt-2 flex gap-1.5">{a.languages.map(l=><span key={l} className="rounded-full bg-canvas px-2 py-0.5 text-[9.5px] text-ink-muted">{l}</span>)}</div></button>)}</div></Card>
<Card><h3 className="mb-3 font-semibold text-ink">Generate alert</h3><form onSubmit={handleSubmit(onSubmit)} className="space-y-3"><input {...register('title',{required:true})} placeholder="Alert title" className="w-full rounded-lg border border-border px-3 py-2.5 text-sm"/><div className="grid grid-cols-2 gap-2.5"><input {...register('event',{required:true})} placeholder="Event type" className="rounded-lg border border-border px-3 py-2.5 text-sm"/><select {...register('severity')} className="rounded-lg border border-border px-3 py-2.5 text-sm"><option>Critical</option><option>High</option><option>Moderate</option></select></div><input {...register('region',{required:true})} placeholder="Region, e.g. Mumbai, Maharashtra" className="w-full rounded-lg border border-border px-3 py-2.5 text-sm"/><textarea {...register('description',{required:true})} rows={2} placeholder="What is happening?" className="w-full rounded-lg border border-border px-3 py-2.5 text-sm"/><textarea {...register('recommendedActions',{required:true})} rows={2} placeholder="What should people/officials do?" className="w-full rounded-lg border border-border px-3 py-2.5 text-sm"/><Button type="submit" className="w-full">Preview explainable alert</Button></form></Card></div>
<Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><ArrowUpRight className="h-4 w-4 text-warning"/> Alert escalation history</div><div className="mt-3 grid gap-2 md:grid-cols-3">{ESCALATION.map((e,i)=><div key={e.time} className="rounded-lg border border-border p-3"><div className="flex justify-between"><span className="text-[11px] font-semibold text-ink">{e.time}</span><span className={`text-[10px] font-bold ${e.level==='Critical'?'text-danger':e.level==='High'?'text-warning':'text-primary'}`}>{e.level}</span></div><p className="mt-1 text-[11px] text-ink-muted">{e.reason}</p>{i>0&&<div className="mt-2 flex items-center gap-1 text-[10px] text-success"><CheckCircle2 className="h-3 w-3"/> Reason recorded</div>}</div>)}</div></Card>
{preview&&<Card><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold text-ink">{preview.title}</h3><p className="text-[11px] text-ink-muted">{preview.region} · {preview.event}</p></div><span className="rounded-full bg-primary-light px-2.5 py-1 text-[10.5px] font-semibold text-primary">CAP-READY ALERT</span></div><div className="mt-4 grid gap-3 lg:grid-cols-3"><div className="rounded-lg bg-canvas p-3"><div className="text-[10px] font-semibold uppercase text-ink-muted">Why this alert?</div><p className="mt-1 text-[11px] text-ink">Triggered by verified incident evidence and impact risk.</p></div><div className="rounded-lg bg-canvas p-3"><div className="text-[10px] font-semibold uppercase text-ink-muted">Action</div><p className="mt-1 text-[11px] text-ink">{preview.recommendedActions}</p></div><div className="rounded-lg bg-canvas p-3"><div className="flex items-center gap-1 text-[10px] font-semibold uppercase text-ink-muted"><Languages className="h-3 w-3"/> Languages</div><p className="mt-1 text-[11px] text-ink">{preview.languages.join(' · ')}</p></div></div><div className="mt-3 flex items-center gap-2 text-[10.5px] text-ink-faint"><ShieldAlert className="h-3.5 w-3.5 text-warning"/> Alert preview prepared for authorized dissemination workflows.</div></Card>}
<Card className="p-3"><div className="flex items-center gap-2 text-[11px] text-ink-muted"><Clock3 className="h-3.5 w-3.5 text-primary"/> Alert fatigue control: only verified or corroborated incidents should automatically qualify for escalation.</div></Card>
</div>}
