import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, AreaChart, Area } from 'recharts'
import { ArrowUpRight, ShieldCheck, TriangleAlert, Users, Target } from 'lucide-react'
import { PageHeader } from '@/components/layout/PageHeader'
import { ChartCard } from '@/components/charts/ChartCard'
import { Card } from '@/components/ui/Card'
import { incidentsByState, severityDistribution, rainfallTrend, hourlySignalDensity, verificationRateTrend, sourceDistribution } from '@/data/analytics'
import { riskForecast } from '@/data/intelligence'
import { GroundTruthPanel } from '@/components/intelligence/GroundTruthPanel'

export default function Analytics() {
  return <div className="space-y-5 p-6">
    <PageHeader title="Weather Analytics" description="Operational analytics: what is happening, how reliable the evidence is, and what may happen next." />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ShieldCheck} label="Verified signal rate" value="91%" hint="+4.2% this week" /><Metric icon={ArrowUpRight} label="Escalating zones" value="7" hint="3 require review" warning /><Metric icon={Users} label="Ground reports" value="2,481" hint="31 new in last 15 min" /><Metric icon={TriangleAlert} label="Ground-truth gaps" value="12" hint="4 significant" danger /></div>
    <GroundTruthPanel />
    <div className="grid gap-5 lg:grid-cols-2">
      <ChartCard title="Next 90-minute risk" question="Is the current incident likely to escalate?"><ResponsiveContainer><AreaChart data={riskForecast}><CartesianGrid strokeDasharray="3 3" stroke="#E3E8F0" /><XAxis dataKey="time" tick={{ fontSize: 11 }} /><YAxis domain={[0,100]} tick={{ fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="risk" stroke="#0B3D91" fill="#EAF1FB" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Impact by category" question="Which real-world systems need attention first?"><div className="space-y-3 pt-2">{[['Roads',89],['Population',72],['Public transport',64],['Power',41]].map(([name,v])=><div key={name}><div className="mb-1 flex justify-between text-[11px]"><span className="font-medium text-ink">{name}</span><span className="text-ink-muted">{v}%</span></div><div className="h-2 overflow-hidden rounded-full bg-canvas"><div className="h-full rounded-full bg-primary" style={{width:`${v}%`}} /></div></div>)}</div></ChartCard>
      <ChartCard title="Incidents by state" question="Which regions have the highest verified incident density?"><ResponsiveContainer><BarChart data={incidentsByState} layout="vertical" margin={{ left: 10 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#E3E8F0" /><XAxis type="number" tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="state" width={90} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="incidents" fill="#0B3D91" radius={[0,4,4,0]} /></BarChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Rainfall trend" question="Is rainfall intensifying this week?"><ResponsiveContainer><LineChart data={rainfallTrend}><CartesianGrid strokeDasharray="3 3" stroke="#E3E8F0" /><XAxis dataKey="day" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Line type="monotone" dataKey="mm" stroke="#0891B2" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Hourly signal density" question="When do ground reports peak?"><ResponsiveContainer><BarChart data={hourlySignalDensity}><CartesianGrid strokeDasharray="3 3" stroke="#E3E8F0" /><XAxis dataKey="hour" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="signals" fill="#0891B2" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></ChartCard>
      <ChartCard title="AI verification rate" question="Is verification keeping pace with incoming signals?"><ResponsiveContainer><LineChart data={verificationRateTrend}><CartesianGrid strokeDasharray="3 3" stroke="#E3E8F0" /><XAxis dataKey="day" tick={{ fontSize: 11 }} /><YAxis domain={[70,100]} tick={{ fontSize: 11 }} /><Tooltip /><Line type="monotone" dataKey="rate" stroke="#16A34A" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Severity distribution" question="How severe are active incidents overall?"><ResponsiveContainer><PieChart><Pie data={severityDistribution} dataKey="value" nameKey="name" innerRadius={50} outerRadius={80}>{severityDistribution.map((d)=><Cell key={d.name} fill={d.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Source distribution" question="Which channels contribute raw signal volume?"><ResponsiveContainer><PieChart><Pie data={sourceDistribution} dataKey="value" nameKey="name" innerRadius={50} outerRadius={80}>{sourceDistribution.map((d)=><Cell key={d.name} fill={d.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard>
    </div>
    <Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><Target className="h-4 w-4 text-primary" /> Forecast vs reality</div><p className="mt-1 text-[11px] text-ink-muted">This comparison will become model evaluation once real backend observations are connected.</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="rounded-lg bg-canvas p-3"><div className="text-[10px] uppercase text-ink-muted">Forecast error</div><div className="mt-1 text-lg font-bold text-ink">8.4%</div></div><div className="rounded-lg bg-canvas p-3"><div className="text-[10px] uppercase text-ink-muted">Impact precision</div><div className="mt-1 text-lg font-bold text-ink">86%</div></div><div className="rounded-lg bg-canvas p-3"><div className="text-[10px] uppercase text-ink-muted">Median verification</div><div className="mt-1 text-lg font-bold text-ink">4.2 min</div></div></div></Card>
  </div>
}
function Metric({ icon: Icon, label, value, hint, warning, danger }: { icon: typeof ShieldCheck; label: string; value: string; hint: string; warning?: boolean; danger?: boolean }) { return <Card className="p-4"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wide text-ink-muted"><Icon className={`h-3.5 w-3.5 ${danger?'text-danger':warning?'text-warning':'text-primary'}`} /> {label}</div><div className="mt-1 text-2xl font-bold text-ink">{value}</div><div className="text-[10.5px] text-ink-faint">{hint}</div></Card> }
