import { useState, useRef } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { MapPin, Camera, Video, Mic, CheckCircle2, X, Loader2, ShieldCheck, Globe2, Navigation } from 'lucide-react'
import { PageHeader } from '@/components/layout/PageHeader'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { reportService } from '@/services/reportService'
import { translationService } from '@/services/translationService'
import type { CitizenReportResult } from '@/types/report'

const EVENTS = ['Heavy Rainfall','Flood','Thunderstorm','Lightning','Heatwave','Fog','Dust Storm','Strong Winds','Waterlogging','Road Blocked','Fallen Tree','Property Damage','Other'] as const
const IMPACTS = ['No visible impact','Road / traffic','Public transport','Residential area','Power / utility','People need help','Property damage'] as const
const LANGUAGES = ['English','Hindi','Marathi','Hinglish','Bengali','Tamil','Telugu','Other'] as const
const schema = z.object({ event: z.enum(EVENTS), locationLabel: z.string().min(2,'Please add a location'), description: z.string().min(3,'Please describe what you see'), impact: z.enum(IMPACTS), language: z.enum(LANGUAGES) })
type FormValues = z.infer<typeof schema>
interface MediaPreview { id:string; type:'image'|'video'; url:string; name:string }

export default function CitizenReports() {
  const { register, handleSubmit, control, setValue, formState:{errors} } = useForm<FormValues>({ resolver:zodResolver(schema), defaultValues:{event:'Heavy Rainfall',locationLabel:'',description:'',impact:'Road / traffic',language:'English'} })
  const [media,setMedia]=useState<MediaPreview[]>([]); const [result,setResult]=useState<CitizenReportResult|null>(null); const [submitting,setSubmitting]=useState(false); const [voiceState,setVoiceState]=useState<'idle'|'processing'|'done'>('idle'); const [voiceResult,setVoiceResult]=useState<{detected:string;translated:string}|null>(null)
  const photoRef=useRef<HTMLInputElement>(null); const videoRef=useRef<HTMLInputElement>(null)
  const onFiles=(files:FileList|null,type:'image'|'video')=>{if(!files)return;const next=Array.from(files).map(f=>({id:`${Date.now()}-${f.name}`,type,url:URL.createObjectURL(f),name:f.name}));setMedia(m=>[...m,...next])}
  const onSubmit=async(values:FormValues)=>{setSubmitting(true);const r=await reportService.createCitizenReport({...values,mediaFiles:[]});setResult(r);setSubmitting(false)}
  const runVoiceDemo=async()=>{setVoiceState('processing');const t=await translationService.translate('Ulwe mein road pe bahut paani bhar gaya hai.','Hindi');setVoiceResult({detected:'Hindi / Hinglish',translated:t});setValue('event','Waterlogging');setValue('description','Road near Ulwe is severely waterlogged');setValue('language','Hinglish');setVoiceState('done')}
  if(result)return <div className="mx-auto max-w-lg p-6"><PageHeader title="Report received" description="Your report is now entering the verification pipeline."/><Card><div className="flex items-center gap-3"><CheckCircle2 className="h-9 w-9 text-success"/><div><div className="font-semibold text-ink">Report {result.reportId}</div><div className="text-[12px] text-ink-muted">AI screening started · {result.submittedAt}</div></div></div><div className="mt-4 space-y-1.5 text-[12.5px]"><Row label="Classified event" value={result.aiClassifiedEvent}/><Row label="Initial evidence" value={`${result.initialEvidenceScore}/100`}/><Row label="Status" value="Under verification"/><Row label="Next step" value="Corroborate nearby reports"/></div><div className="mt-4 rounded-lg bg-primary-light p-3 text-[11.5px] text-primary"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/> Your report can be combined with other nearby reports to create one verified incident.</div><Button className="mt-5" onClick={()=>{setResult(null);setMedia([])}}>Submit another report</Button></Card></div>
  return <div className="mx-auto max-w-2xl p-6"><PageHeader title="Report a Weather Incident" description="Simple, structured and available in your language. Your report becomes useful when location, impact and evidence are clear."/><div className="grid gap-5 lg:grid-cols-[1fr_300px]">
    <div className="space-y-5"><Card><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-ink"><Mic className="h-4 w-4 text-primary"/> Voice-to-Incident</div><p className="mb-3 text-[12.5px] text-ink-muted">Speak naturally in Hindi, Marathi, Hinglish or English. VARSHAA normalizes it into a weather event.</p><Button variant="outline" size="sm" onClick={runVoiceDemo} disabled={voiceState==='processing'}>{voiceState==='processing'?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Mic className="h-3.5 w-3.5"/>}{voiceState==='processing'?'Processing…':'Try voice report'}</Button>{voiceResult&&<div className="mt-3 rounded-lg bg-canvas p-3 text-[12px]"><div><b>Detected:</b> {voiceResult.detected}</div><div className="mt-1"><b>Normalized:</b> {voiceResult.translated}</div><div className="mt-1 text-success">Event and description pre-filled.</div></div>}</Card>
      <Card><form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-2"><div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">What happened?</label><select {...register('event')} className="w-full rounded-lg border border-border px-3 py-2.5 text-sm">{EVENTS.map(e=><option key={e}>{e}</option>)}</select></div><div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">Report language</label><select {...register('language')} className="w-full rounded-lg border border-border px-3 py-2.5 text-sm">{LANGUAGES.map(l=><option key={l}>{l}</option>)}</select></div></div>
        <div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">Location</label><div className="flex gap-2"><Controller name="locationLabel" control={control} render={({field})=><input {...field} placeholder="e.g. Navi Mumbai, Sector 19" className="flex-1 rounded-lg border border-border px-3 py-2.5 text-sm"/>}/><Button type="button" variant="outline" size="sm" onClick={()=>setValue('locationLabel','Navi Mumbai · GPS captured')}><Navigation className="h-3.5 w-3.5"/></Button></div>{errors.locationLabel&&<p className="mt-1 text-[11px] text-danger">{errors.locationLabel.message}</p>}</div>
        <div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">What is the impact?</label><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{IMPACTS.slice(1).map(i=><label key={i} className="rounded-lg border border-border px-2.5 py-2 text-[11px] text-ink hover:bg-canvas"><input type="radio" value={i} {...register('impact')} className="mr-1.5 accent-primary"/>{i}</label>)}</div></div>
        <div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">Describe what you see</label><textarea {...register('description')} rows={3} placeholder="Example: Road near Ulwe is completely waterlogged and traffic has stopped." className="w-full rounded-lg border border-border px-3 py-2.5 text-sm"/>{errors.description&&<p className="mt-1 text-[11px] text-danger">{errors.description.message}</p>}</div>
        <div><label className="mb-1.5 block text-[11.5px] font-semibold text-ink-muted">Evidence (optional but useful)</label><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={()=>photoRef.current?.click()}><Camera className="h-3.5 w-3.5"/> Photo</Button><Button type="button" variant="outline" size="sm" onClick={()=>videoRef.current?.click()}><Video className="h-3.5 w-3.5"/> Video</Button></div><input ref={photoRef} type="file" accept="image/*" multiple hidden onChange={e=>onFiles(e.target.files,'image')}/><input ref={videoRef} type="file" accept="video/*" multiple hidden onChange={e=>onFiles(e.target.files,'video')}/>{media.length>0&&<div className="mt-3 grid grid-cols-3 gap-2">{media.map(m=><div key={m.id} className="group relative overflow-hidden rounded-lg border border-border">{m.type==='image'?<img src={m.url} className="h-20 w-full object-cover"/>:<video src={m.url} className="h-20 w-full object-cover"/>}<button type="button" onClick={()=>setMedia(ms=>ms.filter(x=>x.id!==m.id))} className="absolute right-1 top-1 rounded-full bg-black/60 p-0.5 text-white"><X className="h-3 w-3"/></button></div>)}</div>}<p className="mt-1.5 text-[11px] text-ink-faint">Media will later be checked for duplicates, age, location and weather consistency.</p></div>
        <Button type="submit" className="w-full" disabled={submitting}>{submitting?<Loader2 className="h-4 w-4 animate-spin"/>:null} Submit report</Button>
      </form></Card></div>
    <div className="space-y-3"><Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><ShieldCheck className="h-4 w-4 text-success"/> Your report matters</div><div className="mt-3 space-y-2 text-[11.5px] text-ink-muted"><p>✓ GPS helps cluster nearby reports.</p><p>✓ Structured impact helps estimate severity.</p><p>✓ Photo/video can strengthen evidence.</p><p>✓ Your language is normalized before analysis.</p></div></Card><Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><Globe2 className="h-4 w-4 text-primary"/> Reporter reliability</div><div className="mt-2 text-2xl font-bold text-primary">New reporter</div><p className="mt-1 text-[11px] text-ink-muted">Future reports can build a reliability history. New users are never treated as unreliable simply because they are new.</p></Card><Card><div className="flex items-center gap-2 text-sm font-semibold text-ink"><MapPin className="h-4 w-4 text-warning"/> Privacy</div><p className="mt-2 text-[11px] text-ink-muted">Public incident views can use an approximate location while precise coordinates remain restricted to authorized workflows.</p></Card></div>
  </div></div>
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b border-border py-1.5"><span className="text-ink-muted">{label}</span><span className="font-medium text-ink">{value}</span></div>}
